spring:
  devtools:
    restart.enabled: true
    livereload.enabled: true
  messages:
    basename: messages, errors

server:
  error:
    include-stacktrace: never
  servlet:
    session:
      tracking-modes: cookie

logging:
  level:
    root: info