spring:
  devtools:
    restart.enabled: true
    livereload.enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/datajpa
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true

  data:
    web:
      pageable:
        default-page-size: 10

logging:
  level:
    org.hibernate:
      sql: debug
      type: trace
      orm:
        jdbc:
          bind: trace
