spring:
  profiles:
    active: local
  devtools:
    restart.enabled: true
    livereload.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/querydsl
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
  data:
    web:
      pageable:
        default-page-size: 20

logging:
  level:
    root: info
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
